### ISSUE TITLE
Support trace for simple CAN

### ISSUE THREAD

**Issue by valesQQ** [eclipse/kiso-testing#387]
Hello,
As a developer I use pyKiso to test my embedded C software.
All my communication are done using "simple" CAN and not CAN_FD. I noticed that if I activate the logs to generate a .trc, the test crash when using the parameter ``is_fd: False`. 
With CAN_FD, logs are properly generated.

It was something about "1.1 version of trace which was not supported".
I don't have access to my setup until next week, I will try to provide the exact error message asap.

I stay available if you have any questions or if I can give any info to help :)

**Comment by sebastianpfischer** [comment]
Hi @valesQQ,

Thanks for the info.
Just to make sure, you are using / will use a peak-can dongle right?

@sebclrsn, @Pog3k fyi

**Comment by sebclrsn** [comment]
Hi @valesQQ, could you maybe send us the header of the created PCAN trc file so that we can check which version it has?

**Comment by valesQQ** [comment]
Hi @sebastianpfischer, @sebclrsn,

Yes, we use peak-can dongle to perform the tests.
Below you can find the header of the .trc when running test in CAN_FD.
```
;$FILEVERSION=2.0
;$STARTTIME=45203.7157523148
;$COLUMNS=N,O,T,I,d,L,D
;
;   .\20231004151041_PCAN_USBBUS1_1.trc
;   Start time: 04.10.2023 15:10:41.907.7
;   Driver version: 
;   Generated by PCAN-Basic API, version 4.7.1.818
;-------------------------------------------------------------------------------
;   Connection                 Bit rate
;   PCAN_USBBUS1               f_clock=80000000,nom_brp=2,nom_tseg1=63,nom_tseg2=16,nom_sjw=16,data_brp=4,data_tseg1=7,data_tseg2=2,data_sjw=2
;-------------------------------------------------------------------------------
; Glossary:
;   Direction of Message:
;     Rx: The frame was received
;     Tx: The frame was transmitted
```
When running test in CAN, no trace is generated at all so I don't have any header to provide, sorry
