### ISSUE TITLE
Testapp doesn't work with latest pykiso

### ISSUE THREAD

**Issue by Pog3k** [eclipse/kiso-testing#393]
**In order to** run the *TestApp* with the latest *pykiso* (0.25.0)
**We want to** fix the different issues:
* Connector interface

**Additional information**
Testapp is only compatible with pykiso 0.19.4

**Comment by sebastianpfischer** [comment]
Closed because of a potential new approach we want to take with pykiso: Make the other test-framework call pykiso as test-participants
