### ISSUE TITLE
Update Black Version

### ISSUE THREAD

**Issue by Pog3k** [eclipse/kiso-testing#394]
Dependabot offers a new Black version but the Jenkins Pipe is red because we do an internal format check with an old version.

Todo:
* Update docker file
* Update the pre-commit hook

**Comment by Pog3k** [comment]
we could directly switch to ruff

- repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        exclude: '^examples/|^tests/'
        args: [ "--fix", "--line-length=120"]
      - id: ruff-format
        exclude: '^examples/|^tests/'
        args: [ "--line-length=120"]

**Comment by sebastianpfischer** [comment]
@Pog3k, this seems like new, what is the difference with black?
